name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Build will compile APK, test APK and run tests, lint, etc.
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      TERM: dumb

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
          
    - name: Build and check all modules
      run: ./gradlew assembleDebug assembleDebugAndroidTest lintDebug testDebug

    - name: Upload build reports (direct-share-start)
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: build-reports-direct-share-start
        path: direct-share-start/app/build/reports

    - name: Upload build reports (direct-share-done)
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: build-reports-direct-share-done
        path: direct-share-done/app/build/reports

    # Project have not tests; omitting steps for publishing test artifacts
